### PR TITLE
Linked android code to developers.android.com reference

### PR DESCRIPTION
**Pull request by ManojMadanmohan**
added code to hyperlink android framework classes to the developer reference site.

### CODE REVIEW

**Comment by ManojMadanmohan** [comment]
#7

**Comment by droidchef** [comment]
@ManojMadanmohan Excellent !! That was a quick one :) 

Just one question before I merge, looks like your email is not configured properly. Because the commit author doesn't seem to link to your github account. do you want to fix that before I merge this ? 

If you need help with this let me know.

**Comment by ManojMadanmohan** [comment]
@droidchef I've changed my email. Can you please check and let me know if its fine?

**Comment by droidchef** [comment]
Looks good!

**Comment by ManojMadanmohan** [comment]
Thanks! :)
Any idea when you'll release this?

**Comment by droidchef** [comment]
Already Released ! Should be live now :)

**Comment by ManojMadanmohan** [comment]
That was damn quick! Glad to see it go live :)

**Pull request merged**
